from django.db import models
from django.utils import timezone


class LandOwner(models.Model):
    lbkey = models.CharField(db_index=True, max_length=20, verbose_name='地建號')
    city = models.CharField(max_length=1, verbose_name='縣市')
    area = models.CharField(max_length=2, verbose_name='行政區')
    region = models.CharField(max_length=4, verbose_name='段小段')
    lbnum = models.CharField(max_length=9, verbose_name='子母號')
    regno = models.CharField(max_length=4, verbose_name='登記次序')
    reg_date = models.DateField(blank=True, null=True, verbose_name='登記日期')
    reg_date_str = models.CharField(max_length=255, blank=True, null=True, verbose_name='登記日期(字串)')
    reg_reason = models.CharField(max_length=255, blank=True, null=True, verbose_name='登記原因')
    reason_date = models.DateField(blank=True, null=True, verbose_name='原因發生日期')
    reason_date_str = models.CharField(max_length=255, blank=True, null=True, verbose_name='原因發生日期(字串)')
    name = models.CharField(max_length=255, blank=True, null=True, verbose_name='所有權人姓名')
    o_name = models.CharField(max_length=255, blank=True, null=True)
    uid = models.CharField(max_length=10, blank=True, null=True, verbose_name='統一編號／身份證字號')
    o_uid = models.CharField(max_length=10, blank=True, null=True)
    bday = models.DateField(blank=True, null=True, verbose_name='出生日期')
    bday_str = models.CharField(max_length=255, blank=True, null=True, verbose_name='出生日期(字串)')
    address = models.TextField(blank=True, null=True, verbose_name='住址')
    o_address = models.TextField(blank=True, null=True)
    admin = models.TextField(blank=True, null=True, verbose_name='管理者')
    o_admin = models.TextField(blank=True, null=True)
    right_numerator = models.BigIntegerField(blank=True, null=True, verbose_name='權利範圍分子')
    right_denominator = models.BigIntegerField(blank=True, null=True, verbose_name='權利範圍分母')
    right_str = models.CharField(max_length=255, blank=True, null=True, verbose_name='權利範圍(字串)')
    cert_id = models.CharField(max_length=255, blank=True, null=True, verbose_name='權狀字號')
    related_creditor_regno = models.TextField(blank=True, null=True, verbose_name='相關他項登記次序')
    related_creditor_num = models.IntegerField(default=0, verbose_name='相關他項登記數量')
    other_remark = models.TextField(blank=True, null=True, verbose_name='其他登記事項')
    query_time = models.DateTimeField(verbose_name='查詢日期')
    query_time_str = models.CharField(max_length=255, blank=True, null=True, verbose_name='查詢日期(字串)')
    create_time = models.DateTimeField(default=timezone.now)
    is_valid = models.BooleanField(default=True)
    invalid_time = models.DateTimeField(blank=True, null=True)
    extra = models.TextField(blank=True, null=True)
    declare_value = models.IntegerField(blank=True, null=True, verbose_name='申報地價')
    declare_value_date = models.DateField(blank=True, null=True, verbose_name='申報地價年月')
    declare_value_date_str = models.CharField(max_length=255, blank=True, null=True, verbose_name='申報地價年月(字串)')
    old_value = models.TextField(blank=True, null=True, verbose_name='前次移轉現值或原規定地價')
    land_value_remark = models.TextField(blank=True, null=True, verbose_name='地價備註事項')

    class Meta:
        managed = False
        db_table = 'transcript_landowner'

class BuildingOwner(models.Model):
    lbkey = models.CharField(db_index=True, max_length=20, verbose_name='地建號')
    city = models.CharField(max_length=1, verbose_name='縣市')
    area = models.CharField(max_length=2, verbose_name='行政區')
    region = models.CharField(max_length=4, verbose_name='段小段')
    lbnum = models.CharField(max_length=9, verbose_name='子母號')
    regno = models.CharField(max_length=4, verbose_name='登記次序')
    reg_date = models.DateField(blank=True, null=True, verbose_name='登記日期')
    reg_date_str = models.CharField(max_length=255, blank=True, null=True, verbose_name='登記日期(字串)')
    reg_reason = models.CharField(max_length=255, blank=True, null=True, verbose_name='登記原因')
    reason_date = models.DateField(blank=True, null=True, verbose_name='原因發生日期')
    reason_date_str = models.CharField(max_length=255, blank=True, null=True, verbose_name='原因發生日期(字串)')
    name = models.CharField(max_length=255, blank=True, null=True, verbose_name='所有權人姓名')
    o_name = models.CharField(max_length=255, blank=True, null=True)
    uid = models.CharField(max_length=10, blank=True, null=True, verbose_name='統一編號／身份證字號')
    o_uid = models.CharField(max_length=10, blank=True, null=True)
    bday = models.DateField(blank=True, null=True, verbose_name='出生日期')
    bday_str = models.CharField(max_length=255, blank=True, null=True, verbose_name='出生日期(字串)')
    address = models.TextField(blank=True, null=True, verbose_name='住址')
    o_address = models.TextField(blank=True, null=True)
    admin = models.TextField(blank=True, null=True, verbose_name='管理者')
    o_admin = models.TextField(blank=True, null=True)
    right_numerator = models.BigIntegerField(blank=True, null=True, verbose_name='權利範圍分子')
    right_denominator = models.BigIntegerField(blank=True, null=True, verbose_name='權利範圍分母')
    right_str = models.CharField(max_length=255, blank=True, null=True, verbose_name='權利範圍(字串)')
    cert_id = models.CharField(max_length=255, blank=True, null=True, verbose_name='權狀字號')
    related_creditor_regno = models.TextField(blank=True, null=True, verbose_name='相關他項登記次序')
    related_creditor_num = models.IntegerField(default=0, verbose_name='相關他項登記數量')
    other_remark = models.TextField(blank=True, null=True, verbose_name='其他登記事項')
    query_time = models.DateTimeField(verbose_name='查詢日期')
    query_time_str = models.CharField(max_length=255, blank=True, null=True, verbose_name='查詢日期(字串)')
    create_time = models.DateTimeField(default=timezone.now)
    is_valid = models.BooleanField(default=True)
    invalid_time = models.DateTimeField(blank=True, null=True)
    extra = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'transcript_buildingowner'